# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88a2ba05e5b589839d7fc9e77db07eeca20fa96dc55e0934f8eb14cab8fc01117b664aa9527ef1c162778ee17a46c5086be2fda3ba30700d8f218dff802849c5

test:
  secret_key_base: 7d608cdf1ccbe87f82c203a71a372e4d44b962dc5f98e34afa15d1439242029fedd84022a669b439ee8439fd7fc9a3f9ff71e6739288082e87d7eceef611d8f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
